import "./globals.css";
import { Livvic, Inter } from "next/font/google";
import CustomCursor from "./components/CustomCursor";
import { ThemeProvider } from "@/app/components/theme-provider";
export const metadata = {
  title: "Portfolio Website",
  description: "Generated by create next app",
};
const f = Livvic({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: ["400", "500", "600", "700", "900"],
});
const f2 = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
  weight: ["400", "500", "600", "700", "800"],
});
export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body className="absolute inset-0 -z-10 h-full w-full bg-[#eeeeff] bg-[linear-gradient(to_right,#edddff_1px,transparent_1px),linear-gradient(to_bottom,#edddff_1px,transparent_1px)] dark:bg-[#0c0c0c] dark:bg-[linear-gradient(to_right,#232323_1px,transparent_1px),linear-gradient(to_bottom,#232323_1px,transparent_1px)] bg-[size:7rem_8rem] cursor-none">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CustomCursor />

          <div className="absolute bottom-0 left-0 right-0 top-0 dark:bg-[radial-gradient(circle_1400px_at_50%_50%,transparent,#0c0c0c)] bg-[radial-gradient(circle_1400px_at_50%_50%,transparent,#eeeeff)] ">
            <div
              className={`${f.variable} ${f2.variable} h-screen w-screen dark:text-white text-black`}
            >
              {children}
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
